safe:        false
baseurl:     ""
url: "http://pedromarins.github.io"

name: Pedro Marins
title: Pedro Marins
description: Empreendedor digital e desenvolvedor front-end. Organizador de alguns eventos de tecnologia. Apaixonado por ensinar e viajar.
domain: pedromarins.com
commentlinks: true

source:      .
destination: ./_site
plugins_dir: ./_plugins

twitter_url: http://twitter.com/pedromarins
github_url:  http://github.com/pedromarins
facebook_url:  http://facebook.com/pedrolmarins
linkedin_url:  http://linkedin.com/in/pedromarins

excerpt_separator: "<!--more-->"
permalink: /blog/:title/

livereload: true

markdown: kramdown

sass:
  sass_dir: assets/_sass
  style: compressed